<?php

namespace ferreteria\ZambranoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VentasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ferreteria\ZambranoBundle\Controller\VentasController();
        return $instance;
    }
}
